[package]
name = "tpt-gpu-script-format"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "TPT Script formatter and linter"
license.workspace = true
repository.workspace = true
documentation = "https://docs.rs/tpt-gpu-script-format"
readme = "README.md"
keywords = ["gpu", "compiler", "ml", "ai", "tptscript"]
categories = ["compilers", "development-tools"]

[dependencies]
tpt-gpu-script-core = { path = "../tpt-gpu-script-core", version = "0.1.0" }
serde = { workspace = true }
