"""Rewrite ir.rs from scratch."""
import pathlib

p = pathlib.Path(r"D:\Programming\1PRODUCTION\Open Source\tpt-gpu\layer3_tptc\rust\src\ir.rs")

# Part 1: original IR types and structures
L1 = []
a1 = L1.append
a1("use std::fmt;")
a1("")
a1("#[derive(Debug,Clone,Copy,PartialEq)]")
a1("pub enum AddressSpace{Global,Shared,Local,Constant,Generic}")
a1("impl fmt::Display for AddressSpace{")
a1(" fn fmt(&self,f:&mut fmt::Formatter)->fmt::Result{match self{Self::Global=>write!(f,\"global\"),Self::Shared=>write!(f,\"shared\"),Self::Local=>write!(f,\"local\"),Self::Constant=>write!(f,\"constant\"),Self::Generic=>write!(f,\"generic\")}}")
a1("}")
a1("")
a1("#[derive(Debug,Clone,PartialEq)]")
a1("pub enum TypeKind{I1,I8,I16,I32,I64,F16,BF16,F32,F64,Index,Tensor(Vec<i64>,Box<Type>,AddressSpace),Vector(u32,Box<Type>),MemRef(Vec<i64>,Box<Type>,AddressSpace),Function(Vec<Type>,Vec<Type>),None}")
a1("")
a1("#[derive(Debug,Clone,PartialEq)]")
a1("pub struct Type{pub kind:TypeKind}")
a1("impl Type{")
a1(" pub fn primitive(name:&str)->Self{let kind=match name{\"i1\"=>TypeKind::I1,\"i8\"=>TypeKind::I8,\"i16\"=>TypeKind::I16,\"i32\"=>TypeKind::I32,\"i64\"=>TypeKind::I64,\"f16\"=>TypeKind::F16,\"bf16\"=>TypeKind::BF16,\"f32\"=>TypeKind::F32,\"f64\"=>TypeKind::F64,\"index\"=>TypeKind::Index,_=>TypeKind::None};Type{kind}}")
a1(" pub fn tensor(shape:Vec<i64>,el:Type,addr:AddressSpace)->Self{Type{kind:TypeKind::Tensor(shape,Box::new(el),addr)}}")
a1(" pub fn vector(lanes:u32,el:Type)->Self{Type{kind:TypeKind::Vector(lanes,Box::new(el))}}")
a1(" pub fn memref(shape:Vec<i64>,el:Type,addr:AddressSpace)->Self{Type{kind:TypeKind::MemRef(shape,Box::new(el),addr)}}")
a1("}")
a1("impl fmt::Display for Type{")
a1(" fn fmt(&self,f:&mut fmt::Formatter)->fmt::Result{")
a1("  match&self.kind{")
a1("   TypeKind::I1=>write!(f,\"i1\"),TypeKind::I8=>write!(f,\"i8\"),TypeKind::I16=>write!(f,\"i16\"),TypeKind::I32=>write!(f,\"i32\"),TypeKind::I64=>write!(f,\"i64\"),TypeKind::F16=>write!(f,\"f16\"),TypeKind::BF16=>write!(f,\"bf16\"),TypeKind::F32=>write!(f,\"f32\"),TypeKind::F64=>write!(f,\"f64\"),TypeKind::Index=>write!(f,\"index\"),")
a1("   TypeKind::Tensor(s,e,a)=>{let v:Vec<String>=s.iter().map(|d|if*d<0{\"*\".into()}else{d.to_string()}).collect();write!(f,\"tensor<{}x{}\",v.join(\"x\"),e)?;if*a!=AddressSpace::Global{write!(f,\", {}\",a)?;}write!(f,\">\")}")
a1("   TypeKind::Vector(l,e)=>write!(f,\"vector<{}x{}>\",l,e),")
a1("   TypeKind::MemRef(s,e,a)=>{let v:Vec<String>=s.iter().map(|d|if*d<0{\"*\".into()}else{d.to_string()}).collect();write!(f,\"memref<{}x{}\",v.join(\"x\"),e)?;if*a!=AddressSpace::Global{write!(f,\", {}\",a)?;}write!(f,\">\")}")
a1("   TypeKind::Function(i,o)=>{let a:Vec<String>=i.iter().map(|t|t.to_string()).collect();let b:Vec<String>=o.iter().map(|t|t.to_string()).collect();write!(f,\"({}) -> ({})\",a.join(\", \"),b.join(\", \"))}")
a1("   TypeKind::None=>write!(f,\"none\"),")
a1(" }}}")
a1("")
a1("#[derive(Debug,Clone)]")
a1("pub enum OpKind{Addi,Subi,Muli,Addf,Subf,Mulf,And,Or,Xor,CmpEq,CmpLt,Load,Store,Branch,Return,Constant(String),Custom(String)}")
a1("")
a1("#[derive(Debug,Clone)]")
a1("pub struct Value{pub id:u64,pub typ:Type}")
a1("impl Value{pub fn new(id:u64,typ:Type)->Self{Value{id,typ}}}")
a1("")
a1("#[derive(Debug,Clone)]")
a1("pub struct Operation{pub kind:OpKind,pub operands:Vec<Value>,pub result_type:Option<Type>,pub result_id:Option<u64>}")
a1("impl Operation{")
a1(" pub fn new(kind:OpKind)->Self{Operation{kind,operands:vec![],result_type:None,result_id:None}}")
a1(" pub fn display(&self)->String{")
a1("  match&self.kind{")
a1("   OpKind::Addi=>\"addi\",OpKind::Subi=>\"subi\",OpKind::Muli=>\"muli\",")
a1("   OpKind::Addf=>\"addf\",OpKind::Subf=>\"subf\",OpKind::Mulf=>\"mulf\",")
a1("   OpKind::And=>\"andi\",OpKind::Or=>\"ori\",OpKind::Xor=>\"xori\",")
a1("   OpKind::CmpEq=>\"cmpeq\",OpKind::CmpLt=>\"cmplt\",")
a1("   OpKind::Load=>\"load\",OpKind::Store=>\"store\",")
a1("   OpKind::Branch=>\"br\",OpKind::Return=>\"return\",")
a1("   OpKind::Constant(v)=>return format!(\"constant {}\",v),")
a1("   _=>\"custom\",")
a1("  }.to_string()")
a1(" }")
a1("}")
a1("")
a1("#[derive(Debug,Clone)]")
a1("pub struct Block{pub label:String,pub operations:Vec<Operation>,pub arguments:Vec<Value>}")
a1("impl Block{pub fn new(label:&str)->Self{Block{label:label.to_string(),operations:vec![],arguments:vec![]}}}")
a1("")
a1("#[derive(Debug,Clone)]")
a1("pub struct Region{pub blocks:Vec<Block>}")
a1("impl Region{pub fn new()->Self{Region{blocks:vec![]}}}")
a1("impl fmt::Display for Region{")
a1(" fn fmt(&self,f:&mut fmt::Formatter)->fmt::Result{")
a1("  for b in &self.blocks{writeln!(f,\"^{}: \",b.label)?;for op in &b.operations{writeln!(f,\"  {}\",op.display())?;}}")
a1("  Ok(())")
a1("}")
a1("")
a1("/// Parse a minimal TPTIR-style assembly into a Region.")
a1("pub fn parse_assembly(source:&str)->Result<Region,String>{")
a1(" let mut region=Region::new();")
a1(" let mut block=Block::new(\"entry\");")
a1(" for line in source.lines(){")
a1("  let line=line.trim();")
a1("  if line.is_empty()||line.starts_with(';')||line.starts_with('#'){continue;}")
a1("  if line.starts_with('^'){if!block.operations.is_empty(){region.blocks.push(std::mem::replace(&mut block,Block::new(&line[1..])));}}")
a1(" }")
a1(" if!block.operations.is_empty()||region.blocks.is_empty(){region.blocks.push(block);}")
a1(" Ok(region)")
a1("}")

# Write part 1
p.write_text("\n".join(L1)+"\n", encoding="utf-8")
print(f"wrote part 1: {p.stat().st_size} bytes")

# Write part 1
p.write_text("\n".join(L1)+"\n", encoding="utf-8")
print(f"wrote part 1: {p.stat().st_size} bytes")

# Part 2: new types and functions
L2 = []
a2 = L2.append
a2("")
a2("/// Supported element types for kernel templates.")
a2("#[derive(Debug,Clone,Copy,PartialEq,Hash,Eq)]")
a2("pub enum ElemType{ F32, F16, BF16, I32 }")
a2("impl ElemType{")
a2(" pub fn name(self)->&str{match self{ElemType::F32=>\"f32\",ElemType::F16=>\"f16\",ElemType::BF16=>\"bf16\",ElemType::I32=>\"i32\"}}")
a2(" pub fn parse(s:&str)->Option<Self>{match s{\"f32\"=>Some(ElemType::F32),\"f16\"=>Some(ElemType::F16),\"bf16\"=>Some(ElemType::BF16),\"i32\"=>Some(ElemType::I32),_=>None}}")
a2(" pub fn zero(self)->String{match self{ElemType::F32=>\"0.0\",ElemType::F16=>\"0.0\",ElemType::BF16=>\"0.0\",ElemType::I32=>\"0\"}}")
a2("}")
a2("")
a2("/// A kernel variant: template name + element type + shape parameters.")
a2("#[derive(Debug,Clone,PartialEq,Hash,Eq)]")
a2("pub struct KernelVariant{ pub name:String, pub elem:ElemType, pub shape_params:Vec<i64> }")
a2("impl KernelVariant{")
a2(" pub fn dispatch_key(&self)->String{")
a2("  let ss=self.shape_params.iter().map(|s|s.to_string()).collect::<Vec<_>>().join(\"x\");")
a2("  format!(\"{}_{}_{}\", self.name, self.elem.name(), ss)")
a2(" }")
a2("}")
a2("")
a2("/// Generated variant record: the variant metadata and its TPTIR text.")
a2("#[derive(Debug,Clone)]")
a2("pub struct GeneratedKernel{ pub variant:KernelVariant, pub tptir_text:String, pub entry_name:String }")
a2("")
a2("/// TPTIR assembly operation kinds produced by the TPTIR text emitter.")
a2("#[derive(Debug,Clone,Copy,PartialEq)]")
a2("pub enum TptirOp{ Addi,Subi,Muli,Addf,Subf,Mulf,And,Or,Xor,CmpEq,CmpLt,Load,Store,Branch,Return,Constant,Custom }")
a2("impl TptirOp{")
a2(" pub fn name(self)->&str{match self{")
a2("  TptirOp::Addi=>\"addi\",TptirOp::Subi=>\"subi\",TptirOp::Muli=>\"muli\",")
a2("  TptirOp::Addf=>\"addf\",TptirOp::Subf=>\"subf\",TptirOp::Mulf=>\"mulf\",")
a2("  TptirOp::And=>\"andi\",TptirOp::Or=>\"ori\",TptirOp::Xor=>\"xori\",")
a2("  TptirOp::CmpEq=>\"cmpeq\",TptirOp::CmpLt=>\"cmplt\",")
a2("  TptirOp::Load=>\"load\",TptirOp::Store=>\"store\",")
a2("  TptirOp::Branch=>\"br\",TptirOp::Return=>\"return\",")
a2("  TptirOp::Constant=>\"constant\",TptirOp::Custom=>\"custom\" }}")
a2("}")
a2("")
a2("/// Map a Rust-IR `OpKind` to its TPTIR textual operation name.")
a2("pub fn opkind_to_tptir(op:&OpKind)->TptirOp{")
a2(" match op{")
a2("  OpKind::Addi=>TptirOp::Addi,OpKind::Subi=>TptirOp::Subi,OpKind::Muli=>TptirOp::Muli,")
a2("  OpKind::Addf=>TptirOp::Addf,OpKind::Subf=>TptirOp::Subf,OpKind::Mulf=>TptirOp::Mulf,")
a2("  OpKind::And=>TptirOp::And,OpKind::Or=>TptirOp::Or,OpKind::Xor=>TptirOp::Xor,")
a2("  OpKind::CmpEq=>TptirOp::CmpEq,OpKind::CmpLt=>TptirOp::CmpLt,")
a2("  OpKind::Load=>TptirOp::Load,OpKind::Store=>TptirOp::Store,")
a2("  OpKind::Branch=>TptirOp::Branch,OpKind::Return=>TptirOp::Return,")
a2("  OpKind::Constant(_)=>TptirOp::Constant,OpKind::Custom(_)=>TptirOp::Custom }}")
a2("}")
a2("")
a2("/// Canonical set of supported kernel template names.")
a2("pub const KERNEL_TEMPLATES:[&str]=[\"vector_add\",\"matmul\",\"softmax\",\"flash_attention\",\"conv_bn_relu\"];")

existing = p.read_text(encoding="utf-8")
p.write_text(existing + "\n" + "\n".join(L2) + "\n", encoding="utf-8")
print(f"wrote part 2: {p.stat().st_size} bytes")
# Write part 1
p.write_text("\n".join(L1)+"\n", encoding="utf-8")
print(f"wrote part 1: {p.stat().st_size} bytes")

# Part 2: new types and functions