"""Append emit_tptir and build_kernel_region to ir_tail.rs"""
import pathlib

T = pathlib.Path(r"D:\Programming\1PRODUCTION\Open Source\tpt-gpu\tools\kernel-generator\ir_tail.rs")
existing = T.read_text(encoding="utf-8")

L = []
a = L.append
a("")
a("/// Emit TPTIR textual assembly from a Region (spec v1.0 section 7.1).")
a("pub fn emit_tptir(region:&Region, entry_name:&str, kernel_attrs:&[(String,String)])->String{")
a(" let mut out=String::new();")
a(" out.push_str(&format!(\"module {{\\n  func.func @{}\", entry_name));")
a(" if let Some(entry)=region.blocks.first(){")
a("  if !entry.arguments.is_empty(){")
a("   let args:Vec<String>=entry.arguments.iter().map(|v|format!(\"%{}: {}\", v.id, v.typ)).collect();")
a("   out.push_str(&format!(\"({})\", args.join(\", \")));")
a("  } }")
a(' out.push_str(" attributes {tptir.kernel");')
a(" for (k,v) in kernel_attrs{ out.push_str(&format!(\", {} = {}\", k, v)); }")
a(' out.push_str("} {\\n");')
a(" for block in &region.blocks{")
a('  out.push_str(&format!("    ^{}:\\n", block.label));')
a("  for op in &block.operations{")
a("   let lhs=match op.result_id{Some(id)=>format!(\"%{} = \", id),None=>String::new()};")
a("   let oo=op.operands.iter().map(|v|format!(\"%{}\",v.id)).collect::<Vec<_>>().join(\", \");")
a("   let to=opkind_to_tptir(&op.kind);")
a("   let oper_str=match to{")
a("    TptirOp::Addi|TptirOp::Subi|TptirOp::Muli|TptirOp::Addf|TptirOp::Subf|TptirOp::Mulf|TptirOp::And|TptirOp::Or|TptirOp::Xor=>{")
a("     let ty=op.result_type.as_ref().map(|t|t.to_string()).unwrap_or_default();")
a('     format!("tptir.{}({}) : ({}) -> {}", to.name(), oo, "i32", ty) }')
a('    TptirOp::CmpEq|TptirOp::CmpLt=>format!("tptir.{}({}) : (i32, i32) -> i1", to.name(), oo),')
a('    TptirOp::Load=>format!("tptir.load({})", oo),')
a('    TptirOp::Store=>format!("tptir.store({})", oo),')
a('    TptirOp::Branch=>format!("tptir.br {}", oo),')
a('    TptirOp::Return=>String::from("tptir.return"),')
a("    TptirOp::Constant=>{ let val=match&op.kind{OpKind::Constant(v)=>v.clone(),_=>String::from(\"0\")}; let ty=op.result_type.as_ref().map(|t|t.to_string()).unwrap_or_default(); format!(\"tptir.constant {} : {}\", val, ty) }")
a('    TptirOp::Custom=>String::from(""), };')
a('   if !oper_str.is_empty(){ out.push_str(&format!("      {}{}\\n", lhs, oper_str)); }')
a("  } }")
a(' out.push_str("  }\\n}\\n"); out')
a("}")
a("")
a("/// Build a single-block `Region` from a high-level kernel description.")
a("pub fn build_kernel_region(name:&str, elem:ElemType, _shape_params:&[i64])->Result<Region,String>{")
a(" let mut region=Region::new();")
a(' let mut block=Block::new("entry");')
a(" block.arguments.push(Value::new(0,Type::memref(vec![-1],Type::primitive(elem.name()),AddressSpace::Global)));")
a(" block.arguments.push(Value::new(1,Type::memref(vec![-1],Type::primitive(elem.name()),AddressSpace::Global)));")
a(" block.arguments.push(Value::new(2,Type::memref(vec![-1],Type::primitive(elem.name()),AddressSpace::Global)));")
a(' block.arguments.push(Value::new(3,Type::primitive("i32")));')
a(" match name{")
a('  "vector_add"=>{')
a("   let mut op=Operation::new(OpKind::Addf);")
a("   op.operands.push(block.arguments[0].clone());")
a("   op.operands.push(block.arguments[1].clone());")
a("   op.result_type=Some(Type::primitive(elem.name()));")
a("   op.result_id=Some(10);")
a("   block.operations.push(op);")
a("   let mut ret=Operation::new(OpKind::Return);")
a("   ret.operands.push(Value::new(10,Type::primitive(elem.name())));")
a("   block.operations.push(ret);")
a("  }")
a('  "softmax" | "flash_attention" | "conv_bn_relu" =>{')
a("   let mut op=Operation::new(OpKind::Mulf);")
a("   op.operands.push(block.arguments[0].clone());")
a("   op.operands.push(block.arguments[1].clone());")
a("   op.result_type=Some(Type::primitive(elem.name()));")
a("   op.result_id=Some(10);")
a("   block.operations.push(op);")
a("   let mut ret=Operation::new(OpKind::Return);")
a("   ret.operands.push(Value::new(10,Type::primitive(elem.name())));")
a("   block.operations.push(ret);")
a("  }")
a('  "matmul"=>{')
a("   let mut op=Operation::new(OpKind::Mulf);")
a("   op.operands.push(block.arguments[0].clone());")
a("   op.operands.push(block.arguments[1].clone());")
a("   op.result_type=Some(Type::primitive(elem.name()));")
a("   op.result_id=Some(10);")
a("   block.operations.push(op);")
a("   let mut acc=Operation::new(OpKind::Addf);")
a("   acc.operands.push(Value::new(10,Type::primitive(elem.name())));")
a("   acc.operands.push(block.arguments[2].clone());")
a("   acc.result_type=Some(Type::primitive(elem.name()));")
a("   acc.result_id=Some(11);")
a("   block.operations.push(acc);")
a("   let mut ret=Operation::new(OpKind::Return);")
a("   ret.operands.push(Value::new(11,Type::primitive(elem.name())));")
a("   block.operations.push(ret);")
a("  }")
a('  _=>return Err(format!("Unknown kernel template: {}",name)),')
a(" }")
a(" region.blocks.push(block);")
a(" Ok(region)")
a("}")

T.write_text(existing + "\n" + "\n".join(L) + "\n", encoding="utf-8")
print(f"wrote final: {T.stat().st_size} bytes")

"""Append ir_tail.rs content to ir.rs"""
import pathlib

SRC = pathlib.Path(r"D:\Programming\1PRODUCTION\Open Source\tpt-gpu\layer3_tptc\rust\src\ir.rs")
TAIL = pathlib.Path(r"D:\Programming\1PRODUCTION\Open Source\tpt-gpu\tools\kernel-generator\ir_tail.rs")

src_content = SRC.read_text(encoding="utf-8")
tail_content = TAIL.read_text(encoding="utf-8")

SRC.write_text(src_content + "\n" + tail_content + "\n", encoding="utf-8")
print(f"wrote final ir.rs: {SRC.stat().st_size} bytes")
"""Append ir_tail.rs content to ir.rs"""
import pathlib

SRC = pathlib.Path(r"D:\Programming\1PRODUCTION\Open Source\tpt-gpu\layer3_tptc\rust\src\ir.rs")
TAIL = pathlib.Path(r"D:\Programming\1PRODUCTION\Open Source\tpt-gpu\tools\kernel-generator\ir_tail.rs")

src_content = SRC.read_text(encoding="utf-8")
tail_content = TAIL.read_text(encoding="utf-8")

SRC.write_text(src_content + "\n" + tail_content + "\n", encoding="utf-8")
print(f"wrote final ir.rs: {SRC.stat().st_size} bytes")