"""Generate ir_tail.rs"""
import pathlib
T = pathlib.Path(r"D:\Programming\1PRODUCTION\Open Source\tpt-gpu\tools\kernel-generator\ir_tail.rs")
L = []
a = L.append
a("/// Supported element types for kernel templates.")
a("#[derive(Debug,Clone,Copy,PartialEq,Hash,Eq)]")
a("pub enum ElemType{ F32, F16, BF16, I32 }")
a("impl ElemType{")
a(" pub fn name(self)->&str{match self{ElemType::F32=>\"f32\",ElemType::F16=>\"f16\",ElemType::BF16=>\"bf16\",ElemType::I32=>\"i32\"}}")
a(" pub fn parse(s:&str)->Option<Self>{match s{\"f32\"=>Some(ElemType::F32),\"f16\"=>Some(ElemType::F16),\"bf16\"=>Some(ElemType::BF16),\"i32\"=>Some(ElemType::I32),_=>None}}")
a(" pub fn zero(self)->String{match self{ElemType::F32=>\"0.0\",ElemType::F16=>\"0.0\",ElemType::BF16=>\"0.0\",ElemType::I32=>\"0\"}}")
a("}")
a("")
a("/// A kernel variant: template name + element type + shape parameters.")
a("#[derive(Debug,Clone,PartialEq,Hash,Eq)]")
a("pub struct KernelVariant{ pub name:String, pub elem:ElemType, pub shape_params:Vec<i64> }")
a("impl KernelVariant{")
a(" pub fn dispatch_key(&self)->String{")
a("  let ss=self.shape_params.iter().map(|s|s.to_string()).collect::<Vec<_>>().join(\"x\");")
a("  format!(\"{}_{}_{}\", self.name, self.elem.name(), ss)")
a(" }")
a("}")
a("")
a("/// Generated variant record: the variant metadata and its TPTIR text.")
a("#[derive(Debug,Clone)]")
a("pub struct GeneratedKernel{ pub variant:KernelVariant, pub tptir_text:String, pub entry_name:String }")
a("")
a("/// TPTIR assembly operation kinds produced by the TPTIR text emitter.")
a("#[derive(Debug,Clone,Copy,PartialEq)]")
a("pub enum TptirOp{ Addi,Subi,Muli,Addf,Subf,Mulf,And,Or,Xor,CmpEq,CmpLt,Load,Store,Branch,Return,Constant,Custom }")
a("impl TptirOp{")
a(" pub fn name(self)->&str{match self{")
a("  TptirOp::Addi=>\"addi\",TptirOp::Subi=>\"subi\",TptirOp::Muli=>\"muli\",")
a("  TptirOp::Addf=>\"addf\",TptirOp::Subf=>\"subf\",TptirOp::Mulf=>\"mulf\",")
a("  TptirOp::And=>\"andi\",TptirOp::Or=>\"ori\",TptirOp::Xor=>\"xori\",")
a("  TptirOp::CmpEq=>\"cmpeq\",TptirOp::CmpLt=>\"cmplt\",")
a("  TptirOp::Load=>\"load\",TptirOp::Store=>\"store\",")
a("  TptirOp::Branch=>\"br\",TptirOp::Return=>\"return\",")
a("  TptirOp::Constant=>\"constant\",TptirOp::Custom=>\"custom\" }}")
a("}")
a("")
a("/// Map a Rust-IR `OpKind` to its TPTIR textual operation name.")
a("pub fn opkind_to_tptir(op:&OpKind)->TptirOp{")
a(" match op{")
a("  OpKind::Addi=>TptirOp::Addi,OpKind::Subi=>TptirOp::Subi,OpKind::Muli=>TptirOp::Muli,")
a("  OpKind::Addf=>TptirOp::Addf,OpKind::Subf=>TptirOp::Subf,OpKind::Mulf=>TptirOp::Mulf,")
a("  OpKind::And=>TptirOp::And,OpKind::Or=>TptirOp::Or,OpKind::Xor=>TptirOp::Xor,")
a("  OpKind::CmpEq=>TptirOp::CmpEq,OpKind::CmpLt=>TptirOp::CmpLt,")
a("  OpKind::Load=>TptirOp::Load,OpKind::Store=>TptirOp::Store,")
a("  OpKind::Branch=>TptirOp::Branch,OpKind::Return=>TptirOp::Return,")
a("  OpKind::Constant(_)=>TptirOp::Constant,OpKind::Custom(_)=>TptirOp::Custom }}")
a("}")
a("")
a("/// Canonical set of supported kernel template names.")
a("pub const KERNEL_TEMPLATES:[&str]=[\"vector_add\",\"matmul\",\"softmax\",\"flash_attention\",\"conv_bn_relu\"];")
T.write_text("\n".join(L)+"\n", encoding="utf-8")
print(f"wrote part1: {T.stat().st_size} bytes")
