#ifndef TPT_RUNTIME_CAPI_TPTR_CAPI_H
#define TPT_RUNTIME_CAPI_TPTR_CAPI_H

/* Warning: This file is auto-generated by cbindgen. Do not edit directly. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stddef.h>
#ifdef __cplusplus
extern "C" {
#endif


/**
 * Status codes returned by the C API.
 */
enum tptr_status_t
#if __STDC_VERSION__ >= 202311L
  : int32_t
#endif // __STDC_VERSION__ >= 202311L
 {
    TptrOk = 0,
    ErrorGeneric = -1,
    ErrorOutOfMemory = -2,
    ErrorInvalidAddress = -3,
    ErrorArgumentMismatch = -4,
    ErrorConfiguration = -5,
    ErrorInvalidKernel = -6,
    ErrorNullPointer = -7,
};
#if __STDC_VERSION__ >= 202311L
typedef enum tptr_status_t tptr_status_t;
#else
typedef int32_t tptr_status_t;
#endif // __STDC_VERSION__ >= 202311L

/**
 * Opaque device handle (owns a `Mutex<Device>`).
 */
typedef struct tptr_device_t tptr_device_t;

/**
 * Opaque kernel-launch configuration handle.
 */
typedef struct tptr_kernel_config_t tptr_kernel_config_t;

/**
 * Opaque kernel-launch result handle.
 */
typedef struct tptr_kernel_handle_t tptr_kernel_handle_t;

/**
 * Opaque kernel handle.
 */
typedef struct tptr_kernel_t tptr_kernel_t;

/**
 * Opaque memory allocation handle.
 */
typedef struct tptr_memory_t tptr_memory_t;


tptr_status_t tptr_device_create(uint32_t index,
                                 uint64_t total_memory_bytes,
                                 tptr_device_t **out)
;

 void tptr_device_destroy(tptr_device_t *dev) ;


tptr_status_t tptr_device_allocate(tptr_device_t *dev,
                                   uint64_t size,
                                   uint32_t mem_type,
                                   uint32_t access,
                                   tptr_memory_t **out)
;

 tptr_status_t tptr_device_free(tptr_device_t *dev, tptr_memory_t *mem) ;


tptr_status_t tptr_device_memcpy_htod(tptr_device_t *dev,
                                      tptr_memory_t *dst,
                                      const uint8_t *src,
                                      uint64_t size,
                                      uint64_t dst_offset)
;


tptr_status_t tptr_device_memcpy_dtoh(tptr_device_t *dev,
                                      tptr_memory_t *src,
                                      uint8_t *dst,
                                      uint64_t size,
                                      uint64_t src_offset)
;


tptr_status_t tptr_device_create_kernel(tptr_device_t *dev,
                                        const char *name,
                                        tptr_kernel_t **out)
;


tptr_status_t tptr_device_load_module(tptr_device_t *dev,
                                      const char *tptir_text,
                                      tptr_kernel_t **out)
;

 void tptr_kernel_destroy(tptr_kernel_t *kernel) ;


tptr_status_t tptr_kernel_config_create(uint32_t grid_x,
                                        uint32_t grid_y,
                                        uint32_t grid_z,
                                        uint32_t block_x,
                                        uint32_t block_y,
                                        uint32_t block_z,
                                        tptr_kernel_config_t **out)
;

 void tptr_kernel_config_destroy(tptr_kernel_config_t *cfg) ;


tptr_status_t tptr_device_launch_kernel(tptr_device_t *dev,
                                        tptr_kernel_t *kernel,
                                        tptr_kernel_config_t *cfg,
                                        tptr_kernel_handle_t **out)
;

 void tptr_kernel_handle_destroy(tptr_kernel_handle_t *handle) ;

 bool tptr_kernel_handle_is_complete(tptr_kernel_handle_t *handle) ;

 void tptr_device_synchronize(tptr_device_t *dev) ;

/**
 * Returns the last error message for the calling thread, or NULL if none.
 */
 const char *tptr_last_error(void) ;

/**
 * Frees a string previously returned by `tptr_last_error`.
 */
 void tptr_string_free(char *s) ;

/**
 * Returns the major version of the runtime.
 */
 uint32_t tptr_version_major(void) ;

/**
 * Returns the minor version of the runtime.
 */
 uint32_t tptr_version_minor(void) ;

/**
 * Returns the patch version of the runtime.
 */
 uint32_t tptr_version_patch(void) ;

#endif  /* TPT_RUNTIME_CAPI_TPTR_CAPI_H */
