/// Lowers non-GPU TPT Script functions to Rust source.
///
/// Rewriting rules:
/// - `tpt.xxx(args)` → `tptr::xxx(args)` (runtime dispatch)
/// - `Tensor[f32, m, n]` → `tptr::Tensor<f32>` (shape is runtime metadata)
/// - `[T]` → `&[T]`, `[T; N]` → `[T; N]`, `(T1, T2)` → `(T1, T2)`
/// - Platform types (`Model`, `DataLoader`, …) → `tptr::Model`, etc.
/// - `index` → `usize`, `f16`/`bf16` are left as `f16`/`bf16` (requires
///   an appropriate half-precision crate at the call site)
use crate::ast::*;
use crate::semantic::metadata::extract_function_metadata;

pub struct RustEmitter;

impl RustEmitter {
    pub fn new() -> Self { Self }

    pub fn emit_program(&self, program: &Program) -> String {
        let mut out = String::from("// Generated by tptb — TPT Script → Rust\n\n");

        let has_gpu = program.items.iter().any(|item| {
            if let Item::Function(f) = item {
                extract_function_metadata(f).hardware.requires_gpu
            } else {
                false
            }
        });
        if has_gpu {
            out.push_str(
                "// GPU kernel functions are emitted to TPTIR.\n\
                 // Compile them with: tptc::compile(tptir_source, \"tptisa\")\n\n",
            );
        }

        for item in &program.items {
            let code = match item {
                Item::Import(d) => self.emit_import(d),
                Item::Function(f) => {
                    if extract_function_metadata(f).hardware.requires_gpu {
                        format!("// GPU kernel `{}` → see TPTIR output\n", f.name)
                    } else {
                        self.emit_function(f)
                    }
                }
                Item::TypeAlias(d) => self.emit_type_alias(d),
            };
            out.push_str(&code);
            if !code.ends_with('\n') {
                out.push('\n');
            }
        }

        out
    }

    // -----------------------------------------------------------------------
    // Top-level items
    // -----------------------------------------------------------------------

    fn emit_import(&self, d: &ImportDecl) -> String {
        let path = d.path.join("::");
        match &d.alias {
            Some(alias) => format!("use {path} as {alias};\n"),
            None        => format!("use {path};\n"),
        }
    }

    fn emit_type_alias(&self, d: &TypeDecl) -> String {
        format!("type {} = {};\n", d.name, self.emit_type(&d.ty))
    }

    fn emit_function(&self, f: &FunctionDecl) -> String {
        let meta = extract_function_metadata(f);
        let mut s = String::new();

        if let Some(doc) = &meta.doc {
            s.push_str(&format!("/// {doc}\n"));
        }

        let params: Vec<String> = f
            .params
            .iter()
            .map(|p| format!("{}: {}", p.name, self.emit_type(&p.ty)))
            .collect();

        let ret = f
            .return_type
            .as_ref()
            .map(|t| format!(" -> {}", self.emit_type(t)))
            .unwrap_or_default();

        s.push_str(&format!("pub fn {}({}){} {{\n", f.name, params.join(", "), ret));
        s.push_str(&self.emit_block_body(&f.body, 1));
        s.push_str("}\n");
        s
    }

    // -----------------------------------------------------------------------
    // Block / statement emission
    // -----------------------------------------------------------------------

    fn emit_block_body(&self, block: &Block, indent: usize) -> String {
        let ind = "    ".repeat(indent);
        let mut s = String::new();
        for stmt in &block.stmts {
            let line = self.emit_stmt(stmt, indent);
            s.push_str(&format!("{ind}{line}\n"));
        }
        s
    }

    fn emit_stmt(&self, stmt: &Stmt, indent: usize) -> String {
        match stmt {
            Stmt::Let(l) => {
                let ty_ann = l
                    .ty
                    .as_ref()
                    .map(|t| format!(": {}", self.emit_type(t)))
                    .unwrap_or_default();
                format!("let {}{} = {};", l.name, ty_ann, self.emit_expr(&l.value, indent))
            }
            Stmt::Return(r) => match &r.value {
                Some(e) => format!("return {};", self.emit_expr(e, indent)),
                None    => "return;".to_string(),
            },
            Stmt::Break(_)    => "break;".to_string(),
            Stmt::Continue(_) => "continue;".to_string(),
            Stmt::Expr(e)     => format!("{};", self.emit_expr(e, indent)),
        }
    }

    // -----------------------------------------------------------------------
    // Expression emission
    // -----------------------------------------------------------------------

    fn emit_expr(&self, expr: &Expr, indent: usize) -> String {
        match &expr.kind {
            ExprKind::IntLit(n)    => n.to_string(),
            ExprKind::FloatLit(f)  => {
                // Use suffix to prevent ambiguous float type inference.
                if f.fract() == 0.0 { format!("{f:.1}_f64") } else { format!("{f}_f64") }
            }
            ExprKind::BoolLit(b)   => b.to_string(),
            ExprKind::StringLit(s) => format!("{s:?}"),
            ExprKind::Ident(name)  => name.clone(),

            ExprKind::Paren(inner) => format!("({})", self.emit_expr(inner, indent)),

            ExprKind::ArrayLit(elems) => {
                let parts: Vec<_> = elems.iter().map(|e| self.emit_expr(e, indent)).collect();
                format!("vec![{}]", parts.join(", "))
            }

            ExprKind::BinaryOp { op, left, right } => {
                let lv = self.emit_expr(left, indent);
                let rv = self.emit_expr(right, indent);
                // Range operators must not have spaces: `0..10`, `0..=10`
                match op {
                    BinOp::Range   => format!("{lv}..{rv}"),
                    BinOp::RangeEq => format!("{lv}..={rv}"),
                    _              => format!("{lv} {} {rv}", rust_binop(op)),
                }
            }

            ExprKind::UnaryOp { op, operand } => {
                let op_str = match op { UnOp::Neg => "-", UnOp::Not => "!" };
                format!("{}{}", op_str, self.emit_expr(operand, indent))
            }

            ExprKind::FieldAccess { expr: obj, field } => {
                format!("{}.{}", self.emit_expr(obj, indent), field)
            }

            ExprKind::MethodCall { expr: obj, method, args } => {
                // Rewrite `tpt.xxx(args)` → `tptr::xxx(args)`
                if let ExprKind::Ident(root) = &obj.kind {
                    if root == "tpt" {
                        let args_str = self.emit_call_args(args, indent);
                        return format!("tptr::{}({})", method, args_str);
                    }
                }
                let args_str = self.emit_call_args(args, indent);
                format!("{}.{}({})", self.emit_expr(obj, indent), method, args_str)
            }

            ExprKind::Call { callee, args } => {
                // Rewrite `tpt.xxx(args)` → `tptr::xxx(args)`
                if let Some(fn_name) = tpt_fn_name(callee) {
                    let args_str = self.emit_call_args(args, indent);
                    return format!("tptr::{}({})", fn_name, args_str);
                }
                let callee_str = self.emit_expr(callee, indent);
                let args_str = self.emit_call_args(args, indent);
                format!("{}({})", callee_str, args_str)
            }

            ExprKind::Index { expr: obj, indices } => {
                let obj_str = self.emit_expr(obj, indent);
                // Multi-dimensional index: chain `[i][j]...`
                let idx: Vec<_> = indices.iter().map(|i| self.emit_expr(i, indent)).collect();
                let brackets: String = idx.iter().map(|i| format!("[{i}]")).collect();
                format!("{obj_str}{brackets}")
            }

            ExprKind::If { condition, then_block, else_branch } => {
                let cond = self.emit_expr(condition, indent);
                let ind = "    ".repeat(indent);
                let mut s = format!("if {cond} {{\n");
                s.push_str(&self.emit_block_body(then_block, indent + 1));
                s.push_str(&format!("{ind}}}"));
                if let Some(eb) = else_branch {
                    // else-if emits as `else <expr>` where expr starts with `if ...`
                    s.push_str(&format!(" else {}", self.emit_expr(eb, indent)));
                }
                s
            }

            ExprKind::For { var, iterable, body } => {
                let iter = self.emit_expr(iterable, indent);
                let ind = "    ".repeat(indent);
                let mut s = format!("for {var} in {iter} {{\n");
                s.push_str(&self.emit_block_body(body, indent + 1));
                s.push_str(&format!("{ind}}}"));
                s
            }

            ExprKind::While { condition, body } => {
                let cond = self.emit_expr(condition, indent);
                let ind = "    ".repeat(indent);
                let mut s = format!("while {cond} {{\n");
                s.push_str(&self.emit_block_body(body, indent + 1));
                s.push_str(&format!("{ind}}}"));
                s
            }

            ExprKind::Block(block) => {
                let ind = "    ".repeat(indent);
                let mut s = String::from("{\n");
                s.push_str(&self.emit_block_body(block, indent + 1));
                s.push_str(&format!("{ind}}}"));
                s
            }
        }
    }

    fn emit_call_args(&self, args: &[CallArg], indent: usize) -> String {
        args.iter()
            .map(|a| match a {
                CallArg::Positional(e)             => self.emit_expr(e, indent),
                // Named args have no Rust syntax equivalent; emit as positional
                // with a comment so the intent is preserved.
                CallArg::Named { name, value, .. } => {
                    format!("/*{}=*/ {}", name, self.emit_expr(value, indent))
                }
            })
            .collect::<Vec<_>>()
            .join(", ")
    }

    // -----------------------------------------------------------------------
    // Type emission
    // -----------------------------------------------------------------------

    fn emit_type(&self, ty: &Type) -> String {
        match ty {
            Type::Primitive(p, _) => rust_primitive(p).to_string(),
            Type::Tensor { dtype, .. } => {
                // Shape is runtime metadata; Rust type only carries element type.
                format!("tptr::Tensor<{}>", rust_primitive(dtype))
            }
            Type::Tuple(ts, _) => {
                if ts.is_empty() {
                    "()".to_string()
                } else {
                    let parts: Vec<_> = ts.iter().map(|t| self.emit_type(t)).collect();
                    format!("({})", parts.join(", "))
                }
            }
            Type::Array { elem, size, .. } => {
                format!("[{}; {}]", self.emit_type(elem), size)
            }
            Type::Slice(elem, _) => format!("&[{}]", self.emit_type(elem)),
            Type::Named(name, _) => rust_named_type(name),
        }
    }
}

// -----------------------------------------------------------------------
// Helpers
// -----------------------------------------------------------------------

/// If `callee` is `tpt.<fn>`, return `<fn>`. Otherwise `None`.
fn tpt_fn_name(callee: &Expr) -> Option<&str> {
    if let ExprKind::FieldAccess { expr: base, field } = &callee.kind {
        if let ExprKind::Ident(root) = &base.kind {
            if root == "tpt" {
                return Some(field.as_str());
            }
        }
    }
    None
}

fn rust_primitive(p: &PrimitiveType) -> &'static str {
    match p {
        PrimitiveType::I8    => "i8",
        PrimitiveType::I16   => "i16",
        PrimitiveType::I32   => "i32",
        PrimitiveType::I64   => "i64",
        PrimitiveType::U8    => "u8",
        PrimitiveType::U16   => "u16",
        PrimitiveType::U32   => "u32",
        PrimitiveType::U64   => "u64",
        PrimitiveType::F16   => "f16",
        PrimitiveType::Bf16  => "bf16",
        PrimitiveType::F32   => "f32",
        PrimitiveType::F64   => "f64",
        PrimitiveType::Bool  => "bool",
        PrimitiveType::Index => "usize",
    }
}

fn rust_named_type(name: &str) -> String {
    match name {
        "Model"         => "tptr::Model".to_string(),
        "DataLoader"    => "tptr::DataLoader".to_string(),
        "ComputeStream" => "tptr::ComputeStream".to_string(),
        "Optimizer"     => "tptr::Optimizer".to_string(),
        "Checkpoint"    => "tptr::Checkpoint".to_string(),
        other           => other.to_string(),
    }
}

fn rust_binop(op: &BinOp) -> &'static str {
    match op {
        BinOp::Add     => "+",
        BinOp::Sub     => "-",
        BinOp::Mul     => "*",
        BinOp::Div     => "/",
        BinOp::Mod     => "%",
        BinOp::Eq      => "==",
        BinOp::Ne      => "!=",
        BinOp::Lt      => "<",
        BinOp::Gt      => ">",
        BinOp::Le      => "<=",
        BinOp::Ge      => ">=",
        BinOp::And     => "&&",
        BinOp::Or      => "||",
        BinOp::Range   => "..",
        BinOp::RangeEq => "..=",
    }
}

// -----------------------------------------------------------------------
// Tests
// -----------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::compile_str;

    fn rust_emit(src: &str) -> String {
        let prog = compile_str(src).expect("compile_str");
        RustEmitter::new().emit_program(&prog)
    }

    #[test]
    fn test_simple_fn() {
        let out = rust_emit("fn add(a: f32, b: f32) -> f32 { return a + b }");
        assert!(out.contains("pub fn add(a: f32, b: f32) -> f32"), "{out}");
        assert!(out.contains("return a + b;"), "{out}");
    }

    #[test]
    fn test_tpt_call_rewritten() {
        let out = rust_emit("fn f(x: Tensor[f32, m, n]) { let y = tpt.relu(x) }");
        assert!(out.contains("tptr::relu(x)"), "{out}");
        assert!(!out.contains("tpt.relu"), "{out}");
    }

    #[test]
    fn test_tpt_call_with_named_args() {
        let out = rust_emit("fn f() { let z = tpt.zeros([4, 4], dtype=f32) }");
        assert!(out.contains("tptr::zeros("), "{out}");
    }

    #[test]
    fn test_gpu_fn_skipped() {
        let out = rust_emit("@requires_gpu(true) fn kernel() { }");
        assert!(!out.contains("pub fn kernel"), "{out}");
        assert!(out.contains("GPU kernel `kernel`"), "{out}");
    }

    #[test]
    fn test_import_emitted() {
        let out = rust_emit("import tpt::nn\nfn f() { }");
        assert!(out.contains("use tpt::nn;"), "{out}");
    }

    #[test]
    fn test_tensor_type_mapping() {
        let out = rust_emit("fn f(x: Tensor[f32, m, n]) -> Tensor[f32, m, n] { return x }");
        assert!(out.contains("tptr::Tensor<f32>"), "{out}");
    }

    #[test]
    fn test_doc_comment_emitted() {
        let out = rust_emit(r#"@doc("Compute ReLU") fn relu(x: f32) -> f32 { return x }"#);
        assert!(out.contains("/// Compute ReLU"), "{out}");
    }

    #[test]
    fn test_for_loop() {
        let out = rust_emit("fn f() { for i in 0..10 { let x = i } }");
        assert!(out.contains("for i in 0..10"), "{out}");
    }

    #[test]
    fn test_if_else() {
        let out = rust_emit("fn f(b: bool) -> i32 { if b { return 1 } else { return 0 } }");
        assert!(out.contains("if b"), "{out}");
    }

    #[test]
    fn test_let_with_type_annotation() {
        let out = rust_emit("fn f() { let x: f32 = 1.0 }");
        assert!(out.contains("let x: f32 = "), "{out}");
    }

    #[test]
    fn test_full_matmul_roundtrip() {
        let src = r#"
@doc("Matrix multiply A × B")
@requires_gpu(true)
@constraint("a.shape[1] == b.shape[0]", error="Inner dimensions must match")
fn matmul(a: Tensor[f32, m, k], b: Tensor[f32, k, n]) -> Tensor[f32, m, n] {
    let result = tpt.zeros([m, n], dtype=f32)
    tpt.gemm(a, b, result)
    return result
}

fn scale(x: f32, factor: f32) -> f32 {
    return x * factor
}
"#;
        let out = rust_emit(src);
        // GPU kernel skipped
        assert!(out.contains("GPU kernel `matmul`"), "{out}");
        // Host fn emitted
        assert!(out.contains("pub fn scale(x: f32, factor: f32) -> f32"), "{out}");
    }
}
